stages:
  data_ingestion:
    cmd: python3 src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw

  data_pre:
    cmd: python3 src/data_preprocessing.py
    deps:
      - src/data_ingestion.py
      - src/data_preprocessing.py
    outs:
      - data/processed

